# Homebrew formula for Critical Wormhole Tools
# To install: brew install criticalwormhole/tap/critical-wormhole
# Or: brew tap criticalwormhole/tap && brew install critical-wormhole

class CriticalWormhole < Formula
  include Language::Python::Virtualenv

  desc "Secure network utilities using Magic Wormhole code-based addressing"
  homepage "https://github.com/criticalwormhole/cwt"
  url "https://files.pythonhosted.org/packages/source/c/critical-wormhole/critical-wormhole-0.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"  # Update with actual SHA256 after PyPI release
  license "MIT"
  head "https://github.com/criticalwormhole/cwt.git", branch: "main"

  depends_on "python@3.12"
  depends_on "libsodium"
  depends_on "openssl@3"

  resource "magic-wormhole" do
    url "https://files.pythonhosted.org/packages/source/m/magic-wormhole/magic-wormhole-0.14.0.tar.gz"
    sha256 "PLACEHOLDER"
  end

  resource "asyncssh" do
    url "https://files.pythonhosted.org/packages/source/a/asyncssh/asyncssh-2.14.2.tar.gz"
    sha256 "PLACEHOLDER"
  end

  # Additional resources would be auto-generated by homebrew-pypi-poet

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/wh --help")
    assert_match "nc", shell_output("#{bin}/wh --help")
    assert_match "ssh", shell_output("#{bin}/wh --help")
  end
end
